filter:
  excluded_paths:
    - 'tests/'
    - 'vendor/'

# see https://scrutinizer-ci.com/docs/tools/php/php-scrutinizer/
build:
  nodes:
    php:
      tests:
        override:
          - php-scrutinizer-run --enable-security-analysis
          - command: vendor/bin/phpunit tests/Unit/ --coverage-text --coverage-clover=coverage.clover
            coverage:
              file: coverage.clover
              format: clover
